default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  passwod:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: wasabi_development

test:
  <<: *default
  database: wasabi_test

production:
  <<: *default
  database: wasabi_production
  password: <%= ENV['WASABI_DATABASE_PASSWORD'] %>
